CC=g++

CFLAGS=-std=c++17 -O0 -g \
	-Wall \

EXAMPLES=example1 \
	 example2 \
	 example3 \

all: $(EXAMPLES)

$(EXAMPLES):%:%.cpp
	$(CC) $(CFLAGS) -o $@ $<

clean:
	rm -f example? && rm -rf example?.dSYM/
